### ISSUE TITLE
Database is seeded and objects created, but errors returned for auto generated fields

### ISSUE THREAD

**Issue by robotsrng** [awslabs/amplify-graphql-seed-plugin#23]
Issue:
I'm not sure if this is due to my specific data table set up, but at this point it's all pretty basic so I don't know if that's the case.
When seeding the database, the following error is returned and the "skipped" count is increased by one for all mutations;
`
GraphQL error: Cannot return null for non-nullable field Project._version.
...
...
Added: 0, Skipped: 13, Operation: createProject
`
However, the database is actually seeded, and holds the data. 

Potentially this could be related to [https://github.com/aws-amplify/amplify-cli/issues/2248#issuecomment-780180544]( https://github.com/aws-amplify/amplify-cli/issues/2248#issuecomment-780180544 ) but I'm not sure.

**Comment by mehow-juras** [comment]
Hey @robotsrng, thanks for raising this issue. We're trying to reproduce this bug 🐛   Could you please share your schema.graphql file with us? A code snippet would be great. Also please make sure you remove any PII/confidential data from the file.

**Comment by robotsrng** [comment]
Sorry about that, we've made some changes so I'm no longer receiving this specific issue. I'll get back to you. 

Thanks!

**Comment by mehow-juras** [comment]
I'll close down this issue in that case. However if you manage to reproduce the steps please reopen this issue and we'll act accordingly 👍  Thanks!
